[package]
name = "actix-web-starter"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "3.3.3"
env_logger = "0.9"
serde = "1.0.136"
derive_more = "0.99.17"
serde_json = "1.0.78"
actix-rt = "2.6.0"
